<?php

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\event\Entity\Event;

/**
 * Implements hook_update_dependencies().
 */
function event_update_dependencies() {
  // The update function that adds the status field must run after
  // my_module_update_8103() which fixes NULL values for the
  // 'content_translation_status' field.
  if (\Drupal::moduleHandler()->moduleExists('content_translation')) {
    $dependencies['event'][8103] = [
      'content_translation' => 8400,
    ];

    return $dependencies;
  }
}

/**
 * Update event type config to be just 'type'
 */
function event_update_8101() {
  $config_factory = \Drupal::configFactory();
  $configs = $config_factory->listAll('event.event_type');
  foreach ($configs AS $config) {
    $event_config = $config_factory->getEditable($config);
    $event_config->setName(preg_replace('/event.event_type/', 'event.type', $config));
    $event_config->save();
  }
}

/**
 * Install the Machine Name, Date Range, and Description Fields.
 */
function event_update_8102() {
  $entity_type_manager = \Drupal::entityTypeManager();
  $bundle_of = 'event';

  $storage = $entity_type_manager->getStorage($bundle_of);
  $bundle_definition = $entity_type_manager->getDefinition($bundle_of);
  // Sometimes the primary key isn't 'id'. e.g. 'eid' or 'item_id'.
  $id_key = $bundle_definition->getKey('id');
  // If there is no data table defined then use the base table.
  $base_table_name = $storage->getDataTable() ?: $storage->getBaseTable();
  $revision_table_name = $storage->getRevisionDataTable() ?: $storage->getRevisionTable();
  $database = \Drupal::database();
  $definition_manager = \Drupal::entityDefinitionUpdateManager();

  // Get the existing storage definitions. If they don't exist, we cannot do
  // anything in regards to data import.
  $event_start_field_storage_definition = $definition_manager->getFieldStorageDefinition('event_start', $bundle_of);
  $event_end_field_storage_definition = $definition_manager->getFieldStorageDefinition('event_end', $bundle_of);

  if (isset($event_end_field_storage_definition) && isset($event_start_field_storage_definition)) {
    // Store the existing values. Note we ignore event end timezones. If they were
    // different, sorry, you don't get two TZs on a single event anymore.
    $event_date_values = $database->select($base_table_name)
      ->fields($base_table_name, [$id_key, 'event_start__value', 'event_start__timezone', 'event_end__value'])
      ->execute()
      ->fetchAllAssoc($id_key);

    $event_date_revision_values = $database->select($revision_table_name)
      ->fields($revision_table_name, [$id_key, 'event_start__value', 'event_start__timezone', 'event_end__value'])
      ->execute()
      ->fetchAllAssoc($id_key);

    // Clear out the values.
    $database->update($base_table_name)
      ->fields(['event_start__value' => NULL, 'event_start__timezone' => NULL, 'event_end__value' => NULL, 'event_end__timezone' => NULL])
      ->execute();

    $definition_manager->uninstallFieldStorageDefinition($event_start_field_storage_definition);
    $definition_manager->uninstallFieldStorageDefinition($event_end_field_storage_definition);
  }

  // Create a new field definition.
  $current_fields = Event::baseFieldDefinitions($bundle_definition);

  // make sure 'event date' actually exists as a field.
  if (isset($current_fields['event_date']) && !$definition_manager->getFieldStorageDefinition('event_date', 'event')) {
    // Install the new definition.
    $definition_manager->installFieldStorageDefinition('event_date', $bundle_of, $bundle_of, $current_fields['event_date']);
  }

  // Install the machine name field if it doesn't exist yet.
  if (isset($current_fields['machine_name']) && !$definition_manager->getFieldStorageDefinition('machine_name', 'event')) {
    // Install the new definition.
    $definition_manager->installFieldStorageDefinition('machine_name', $bundle_of, $bundle_of, $current_fields['machine_name']);
  }

  // Install the description field if it doesn't exist yet.
  $description_field = \Drupal::configFactory()->get('field.storage.event.description');
  if ($description_field->isNew()) {
    \Drupal::service('config.installer')->installDefaultConfig('module', 'event');

    // Install the new definition.
    $bundles = \Drupal::service('entity_type.bundle.info')->getBundleInfo('event');
    foreach (array_keys($bundles) as $bundle) {
      // Load the event type
      $event_type = \Drupal::entityTypeManager()->getStorage('event_type')->load($bundle);
      event_add_description_field($event_type);
    }
  }

  // Restore Base values, if we actually have anything to restore.
  if (!empty($event_date_values) && !empty($event_date_revision_values)) {
    foreach ($event_date_values as $id => $row) {
      $database->update($base_table_name)
        ->fields([
          'event_date__value' => $row->event_start__value,
          'event_date__end_value' => $row->event_end__value,
          'event_date__timezone' => $row->event_start__timezone
        ])
        ->condition($id_key, $id)
        ->execute();
    }

    // Restore Revision values
    foreach ($event_date_revision_values as $id => $row) {
      $database->update($revision_table_name)
        ->fields([
          'event_date__value' => $row->event_start__value,
          'event_date__end_value' => $row->event_end__value,
          'event_date__timezone' => $row->event_start__timezone
        ])
        ->condition($id_key, $id)
        ->execute();
    }
  }
}

/**
 * Add the 'published' and revisionable metadata fields to event.
 */
function event_update_8103() {
  $definition_update_manager = \Drupal::entityDefinitionUpdateManager();

  // Add the published entity key and revisionable metadata fields to the
  // event entity type.
  $entity_type = $definition_update_manager->getEntityType('event');
  $entity_type_id = $entity_type->id();

  $entity_keys = $entity_type->getKeys();
  $entity_keys['published'] = 'status';
  $entity_type->set('entity_keys', $entity_keys);

  $revision_metadata_keys = [
    'revision_user' => 'revision_user',
    'revision_created' => 'revision_created',
    'revision_log_message' => 'revision_log_message'
  ];
  $entity_type->set('revision_metadata_keys', $revision_metadata_keys);

  $definition_update_manager->updateEntityType($entity_type);

  // Add the status field.
  $status = BaseFieldDefinition::create('boolean')
    ->setLabel(t('Publishing status'))
    ->setDescription(t('A boolean indicating the published state.'))
    ->setRevisionable(TRUE)
    ->setTranslatable(TRUE)
    ->setDefaultValue(TRUE);

  $has_content_translation_status_field = \Drupal::moduleHandler()->moduleExists('content_translation') && $definition_update_manager->getFieldStorageDefinition('content_translation_status', $entity_type_id);
  if ($has_content_translation_status_field) {
    $status->setInitialValueFromField('content_translation_status');
  }
  else {
    $status->setInitialValue(TRUE);
  }
  $definition_update_manager->installFieldStorageDefinition('status', $entity_type_id, $entity_type_id, $status);

  // Add the revision metadata fields.
  $revision_created = BaseFieldDefinition::create('created')
    ->setLabel(t('Revision create time'))
    ->setDescription(t('The time that the current revision was created.'))
    ->setRevisionable(TRUE);
  $definition_update_manager->installFieldStorageDefinition('revision_created', $entity_type_id, $entity_type_id, $revision_created);

  $revision_user = BaseFieldDefinition::create('entity_reference')
    ->setLabel(t('Revision user'))
    ->setDescription(t('The user ID of the author of the current revision.'))
    ->setSetting('target_type', 'user')
    ->setRevisionable(TRUE);
  $definition_update_manager->installFieldStorageDefinition('revision_user', $entity_type_id, $entity_type_id, $revision_user);

  $revision_log_message = BaseFieldDefinition::create('string_long')
    ->setLabel(t('Revision log message'))
    ->setDescription(t('Briefly describe the changes you have made.'))
    ->setRevisionable(TRUE)
    ->setDefaultValue('')
    ->setDisplayOptions('form', [
      'type' => 'string_textarea',
      'weight' => 25,
      'settings' => [
        'rows' => 4,
      ],
    ]);
  $definition_update_manager->installFieldStorageDefinition('revision_log_message', $entity_type_id, $entity_type_id, $revision_log_message);

  // Uninstall the 'content_translation_status' field if needed.
  $database = \Drupal::database();
  if ($has_content_translation_status_field) {
    // First we have to remove the field data.
    $database->update($entity_type->getDataTable())
      ->fields(['content_translation_status' => NULL])
      ->execute();

    // A site may have disabled revisionability for this entity type.
    if ($entity_type->isRevisionable()) {
      $database->update($entity_type->getRevisionDataTable())
        ->fields(['content_translation_status' => NULL])
        ->execute();
    }

    $content_translation_status = $definition_update_manager->getFieldStorageDefinition('content_translation_status', $entity_type_id);
    $definition_update_manager->uninstallFieldStorageDefinition($content_translation_status);
  }

  return t('@entity_type_label has been converted to revisionable and publishable.', ['@entity_type_label' => $entity_type->getLabel()]);
}
